#! /usr/bin/env python3

num = 1

while True:
    if num % 3 == 0 and num % 5 == 0:
        print('Fizz Buzz!')
        num += 1
    elif num % 3 == 0:
        print('Fizz!')
        num += 1
    elif num % 5 == 0:
        print('Buzz!')
        num += 1
    else:
        print(num)
        num += 1
        if num >= 100:
            break
